### ISSUE TITLE
Understanding fitted function in binomial model

### ISSUE THREAD

**Issue by jroberayalas** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#11]
Hi! Sorry for the silly question. I've been following this repository while reading the Statistical Rethinking book. I finally reached Ch10 and I've a question regarding the fitted values of a binomial model. I have this (your) code:

```
library(rethinking)
data(UCBadmit)
d <- UCBadmit
detach(package:rethinking)
library(brms)
rm(UCBadmit)

d <- 
    d %>%
    mutate(male = ifelse(applicant.gender == "male", 1, 0))

m10.6 <- brm(admit | trials(applications) ~ 1 + male, data = d, family = binomial,
             prior = c(set_prior("normal(0, 10)", class = "Intercept"),
                       set_prior("normal(0, 10)", class = "b")),
             iter = 2500, warmup = 500, cores = 2, chains = 2)
```

which is implementing the following model:

<img width="337" alt="captura de pantalla 2018-04-29 a la s 19 29 07" src="https://user-images.githubusercontent.com/8128586/39409694-a041bafe-4be3-11e8-90c0-61f9226f11d8.png">

When I ran `head(predict(m10.6))`, I get the following table, which are the results of the summary statistics from computing `rbinom(length_of_chain, number_of_applications, invlogit(evaluation_m10.6_per_chain_value))`, i.e. summarising the samples from the first line in the model. Basically, I can replicate this table.

```
      Estimate Est.Error 2.5%ile 97.5%ile
[1,] 367.45325 16.026807     336      398
[2,]  32.83225  4.899144      24       43
[3,] 249.29800 13.106969     223      275
[4,]   7.56750  2.329657       3       12
[5,] 144.88200  9.530466     126      164
[6,] 180.04175 12.949901     154      205
```

However, when I ran `fitted(predict(m10.6))`, the results are the following, but I cannot understand how these estimated errors and percentiles are computed. 

```
       Estimate Est.Error    2.5%ile   97.5%ile
[1,] 367.289295 7.9252189 352.243511 382.861665
[2,]  32.741944 1.1580285  30.418559  34.980130
[3,] 249.311521 5.3795425 239.098625 259.881858
[4,]   7.579154 0.2680622   7.041333   8.097252
[5,] 144.689722 3.1220559 138.762595 150.824292
[6,] 179.777528 6.3584342 167.020420 192.066827
```

Any explanation on this is highly appreciated.

**Comment by ASKurz** [comment]
If I follow, it seems like you’re asking about the distinction between `predict()` and `fitted()`. From the *predict* subsection of the [brms reference manual](https://cran.r-project.org/web/packages/brms/brms.pdf):

> Predict responses based on the fitted model. Can be performed for the data used to fit the model (posterior predictive checks) or for new data. By definition, these predictions have higher variance than predictions of the fitted values (i.e., the ’regression line’) performed by the fitted method. This is because the measurement error is incorporated. The estimated means of both methods should, however, be very similar.

**Comment by jroberayalas** [comment]
Thanks for your reply! I understand that, in the case of a linear regression model, the measurement error is incorporated via the sigma value, i.e. N(mu, sigma). In the case of the binomial model, do you know where this measurement error is coming from?

**Comment by ASKurz** [comment]
It's been a bit since I've updated them, but you might also look at [my vignettes](https://osf.io/z9vr8/) on how to work with `fitted()` and `predict()`. I stick to the Gaussian, but the vignettes might still clarify the distinction, here.

**Comment by ASKurz** [comment]
Ah. Okay. I see what you're saying. My math stats isn't strong enough to give you a satisfying answer. My sense is that in this situation you might think of it as simulation variance.

**Comment by ASKurz** [comment]
For reference, Paul addressed the question [here](https://github.com/paul-buerkner/brms/issues/419).
