### ISSUE TITLE
Adopt "file" argument of brm

### ISSUE THREAD

**Issue by paul-buerkner** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#17]
In the current release version of brms (2.5.0) you can now store and recover your fitted model objects automatically via `brm`. If you like, you could add that when discussing to save model objects in chapter 15.

**Comment by ASKurz** [comment]
I haven't played around with that argument, yet. But I'll augment that part of chapter 15 once I have. Hopefully in the next update.

**Comment by ASKurz** [comment]
[Added](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse/commit/dd462fbda6c518c4728f7d8a0c7fe9c0fcc6234c). It'll sow up in the upcoming bookdown update.
