### ISSUE TITLE
expose_functions() does not work

### ISSUE THREAD

**Issue by shigesong** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#19]
Line 1135 of 11.Rmd, the code:
> expose_functions(b11.5, vectorize = TRUE)
Produced error message of:
> Error in (function (classes, fdef, mtable)  : 
>  unable to find an inherited method for function ‘get_stancode’ for signature ‘"stanmodel"’
I am using rstan 2.18, which I compiled myself. This might be the problem?

**Comment by ASKurz** [comment]
Hmmm. I'm currently using rstan 2.17.3. So yes, that'd be my first guess. This might be a good question for the Stan Forums under the brms tag: https://discourse.mc-stan.org/c/interfaces/brms

**Comment by ASKurz** [comment]
Were you able to get an answer to the question or find a workaround?

**Comment by shigesong** [comment]
https://github.com/paul-buerkner/brms/issues/536#issuecomment-431073328

**Comment by shigesong** [comment]
The new github version of rstan seems to fix the problem.

**Comment by ASKurz** [comment]
That's great; thanks for the update!
