### ISSUE TITLE
Use of mi() when not needed (14.2.1)

### ISSUE THREAD

**Issue by torkar** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#21]
Excellent resource you have! I found something which I think is not correct. In 14.2.1 you declare `b_model`. I think the line that reads:
`bf(kcal      | mi() ~ 1 + mi(neocortex) + logmass) +`

should read
`bf(kcal ~ 1 + mi(neocortex) + logmass) +`

since kcal has no missingness. I don't think it affects the results, but it can be confusing.

**Comment by ASKurz** [comment]
Thanks for the heads up! I should have some time to dive into it, today.

**Comment by ASKurz** [comment]
The fix is in the updated .Rmd file https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse/commit/f69f0083d5f449ec107157fc4550b48b742fc795. It should show up in the next bookdown update, perhaps sometime between now and spring.
