### ISSUE TITLE
Simplification of figure 12.2.a

### ISSUE THREAD

**Issue by RishiSadhir** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#23]
Thanks so much for this project, I found it immensely helpful. I wanted to suggest a more tidyversey way of creating figure 12.2.a:

```
# Draw 100 samples from the posterior
post <- posterior_samples(b12.2, subset = 1:100) %>%
  transmute(alpha = inv_logit_scaled(b_Intercept),
            sigma = inv_logit_scaled(sd_tank__Intercept))

# draw 1000 random numbers for each posterior sample
map2_dfc(post$alpha, post$sigma, ~rnorm(1e3, .x, .y)) %>% 
  gather %>% 
  ggplot(aes(x = value, group = key)) +
    geom_line(stat = "density", alpha = .2) +
    xlab("log-odds survival")
```
![fig](https://user-images.githubusercontent.com/2656570/53688271-7c41c680-3d0f-11e9-9f9f-0078d77c277e.png)

Hope you find this useful!

**Comment by ASKurz** [comment]
That’s a great suggestion! I played around with different solutions to that kind of plot in a [recent blog](https://solomonkurz.netlify.com/post/make-rotated-gaussians-kruschke-style/) and this is a nice addition to those methods. Thanks for bringing it to my attention. Before I release the next revision of the Rethinking project, I’ll update this plot, for sure.

**Comment by ASKurz** [comment]
I ultimately went with a [different solution](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse/commit/ff509de333a80e3cf8709b7673c0f749e559fac0). But the spirit is the same. It'll appear in the upcoming bookdown update. Thanks again for opening the issue.

**Comment by gglee4ai** [comment]
There are some zigzags in Fig. 12.2.a. I am not sure what is the reason. But the set.seed and sample_n affected the pattern. Please check the figure.

**Comment by ASKurz** [comment]
What seed values gave you noticeably different results?

**Comment by gglee4ai** [comment]
I reproduced the graph in my PC.
I guess there is a problem in (sample_n, expand, nesting)

## Fig. 12.2.b with zig-zag lines 
sample_n: 35

```
set.seed(12)
post %>%
  sample_n(35, replace = FALSE) %>%
  expand(nesting(iter, b_Intercept, sd_tank__Intercept),
    x = seq(-4, 5, length.out = 100)
  ) %>%
  mutate(
    y = dnorm(x, b_Intercept, sd_tank__Intercept)
  ) %>%
  ggplot(aes(x = x, y = y, group = iter)) +
  geom_line(alpha = .5, color = "orange2") +
  labs(
    title = "Population survival distribution",
    subtitle = "The Gaussians are on the log-odds scale."
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(-3, 4)) +
  theme_fivethirtyeight() +
  theme(
    plot.title = element_text(size = 13),
    plot.subtitle = element_text(size = 10)
  )
```
https://raw.githubusercontent.com/gglee4ai/public/master/sample35.png


## Fig. 12.2.b without zig-zag lines 
sample_n: 30

```
set.seed(12)
post %>%
  sample_n(30, replace = FALSE) %>%
  expand(nesting(iter, b_Intercept, sd_tank__Intercept),
    x = seq(-4, 5, length.out = 100)
  ) %>%
  mutate(
    y = dnorm(x, b_Intercept, sd_tank__Intercept)
  ) %>%
  ggplot(aes(x = x, y = y, group = iter)) +
  geom_line(alpha = .5, color = "orange2") +
  labs(
    title = "Population survival distribution",
    subtitle = "The Gaussians are on the log-odds scale."
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(-3, 4)) +
  theme_fivethirtyeight() +
  theme(
    plot.title = element_text(size = 13),
    plot.subtitle = element_text(size = 10)
  )
```
https://raw.githubusercontent.com/gglee4ai/public/master/sample30.png
