### ISSUE TITLE
Chapter 3 typo - n_tirals -> n_trials

### ISSUE THREAD

**Issue by colinquirk** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#24]
I know nothing about bookdown or I would just make a pull request. In multiple places in the code in chapter 3 there is an `n_tirals` variable, which should presumably be `n_trials`.

**Comment by ASKurz** [comment]
Good catch. I'll give it a thorough check.

**Comment by ASKurz** [comment]
Updated.
