### ISSUE TITLE
Section 7.5 typo: water.c -> water_c

### ISSUE THREAD

**Issue by js-oh** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#27]
I am really enjoying your work! It's such a nice source to learn both tidyverse syntax and brms. It's especially inspirational to see another psychologist's work here (I'm majoring in counseling psychology, btw).

Just a minor typo to report. In the last part of the section 7.5, 'water.c' needs to be 'water_c,' which will generate the intended plot.

**Comment by ASKurz** [comment]
Thank you for the kind words. I'm glad the work is of use statistically and otherwise.

Great catch! I thought I got them all... I'll fix the typo in the next update.
