### ISSUE TITLE
Section 4.4.3.4 typo

### ISSUE THREAD

**Issue by js-oh** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#28]
Another minor typo to report.

At Section 4.4.3.4., It says, "With fitted(), it’s quite easy to plot a regression line and its intervals. Just omit the summary = T argument." I believe "summary = T" should be "summary = F".

Thanks!

**Comment by ASKurz** [comment]
That's a good catch! The correction will appear in the next update.
