### ISSUE TITLE
Size of repo

### ISSUE THREAD

**Issue by wolski** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#30]
Just cloned the repository today. Took hours. Size of folder is 6.12 GB (6,576,313,925 bytes). Why? Do I need the _book _bookdown_files folder to build the book?

**Comment by ASKurz** [comment]
My technical knowledge on questions like that isn’t the best. I suspect it’s because I typically cache my model fits. Especially for the multilevel models, those can get pretty large.
