### ISSUE TITLE
Error when building the index.Rmd

### ISSUE THREAD

**Issue by wolski** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#31]
The error is.
Should the _main.Rmd be part of the repo?

```
The file _main.Rmd exists. Please delete it if it was automatically generated, or set a different book_filename option in _bookdown.yml.
```

**Comment by ASKurz** [comment]
Yeah. If you’re building the book, you have to delete that file beforehand if it already exists. As to whether it should be part of the repo, keeping it is consistent with my current approach. However, I might avoid the problem by using `delete_merged_file: true` in the `_bookdown.yml` in the next update. See [here](https://github.com/rstudio/bookdown/issues/442).
