### ISSUE TITLE
Section 3.2.2 normalizing constant typo (?)

### ISSUE THREAD

**Issue by chang-hu** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#35]
Thank you very much for this wonderful project! It is very helpful. 

One question in section 3.2.2:
<img width="831" alt="Screen Shot 2019-11-20 at 2 31 07 PM" src="https://user-images.githubusercontent.com/36124585/69276202-9ecc8600-0ba3-11ea-8079-ea99c481d4d3.png">

Should it be `mutate(posterior  = (likelihood * prior) / sum(likelihood * prior))` instead, or `mutate(posterior  = likelihood * prior, posterior = posterior / sum(posterior))`?

**Comment by ASKurz** [comment]
Looks like you sorted it out.
