### ISSUE TITLE
A minor ggplot() code update

### ISSUE THREAD

**Issue by troysgit** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#48]
Hi, 
Thoroughly enjoying working through this book and just wanted to out a very minor thing: 
I was getting "Error in zero_range(range): x must be length 1 or 2" in when plotting the 4 steps, 8 steps and 16 steps plots in Ch. 4.1.1. This is fixed by changing, coord_cartesian(xlim = -6:6), to, coord_cartesian(xlim = c(-6,6)), for the three plots. 
I know it's a very minor point but just wanted to mention it for keeping code up to date. 
Thanks for the great resource!

**Comment by ASKurz** [comment]
Hey @troysgit, thanks for reaching out. Your comment makes me think you're using an outdated link. I think you'll find that code has been corrected if you use this link instead: https://bookdown.org/content/3890/. Please let me know if this does indeed fix the problem.
