### ISSUE TITLE
Section 4.4.3.4. Predictions for E{height} at a given weight.

### ISSUE THREAD

**Issue by dipetkov** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#50]
In this code snippet:
``` r
mu_at_50 <- 
  post %>% 
  transmute(mu_at_50 = b_Intercept + b_weight_c + 5.01)
```
Is the formula for `mu_at_50` correct?

Or should we compute it as `mu_at_50 = b_Intercept + b_weight_c * 5.01`?

**Comment by ASKurz** [comment]
What link are you using? The current link is https://bookdown.org/content/3890/

**Comment by dipetkov** [comment]
I have the second edition, so it's this link: https://bookdown.org/content/4857/. 
It's also more recent, 2022-09-28 vs 2020-10-11, so I assumed most up-to-date.

**Comment by ASKurz** [comment]
Ah, now I see what's going on. This is the GitHub repo for the first edition. Please open up an issue in the repo for the second edition, and I'll address it there. 

https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed/issues
