### ISSUE TITLE
Model 14.1.

### ISSUE THREAD

**Issue by ASKurz** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#9]
Not sure how to get the `div_est` parameters from brms the way McElreath did for his model 14.1. (page 428).

**Comment by paul-buerkner** [comment]
If you use `div_obs | mi(div_sd) ~ ...` as in #10 and specify `save_mevars = TRUE` in `brm`, the parameters will be named `Yl`.

**Comment by ASKurz** [comment]
Worked like a charm. Thanks Paul!
